version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - #
      - echo ${SPECIFIC_FOLDER}
      - |
        #!/bin/bash
        if [ -z "$SPECIFIC_FOLDER_PATH" ]; then
          echo "Starting full s3 sync..."
          #aws s3 sync s3://raw-source s3://sync-destination --delete
        else
          echo "Starting sync for only provided s3 folder path $SPECIFIC_FOLDER_PATH"
          #aws s3 sync s3://raw-source s3://sync-destination --delete --exclude '*' --include '$SPECIFIC_FOLDER_PATH'
          aws s3 ls
        fi
  post_build:
    commands:
      - echo Build completed on `date`
