version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - #
      - echo ${SPECIFIC_FOLDER}
      - |
        #!/bin/bash
        if [ -z "$SPECIFIC_FOLDER_PATH" ]; then
          echo "Starting full s3 sync..."
          aws s3 sync s3://dev-dl-970892252496-us-east-1-raw/consolidated_raw/customer_profile/ s3://dev-dl-970892252496-us-east-1-conformed/sync_test/customer_profile/ --delete
          aws s3 sync s3://dev-dl-970892252496-us-east-1-raw/consolidated_raw/product_profile/ s3://dev-dl-970892252496-us-east-1-conformed/sync_test/product_profile/ --delete
          aws s3 sync s3://dev-dl-970892252496-us-east-1-raw/consolidated_raw/sales_order/ s3://dev-dl-970892252496-us-east-1-conformed/sync_test/sales_order/ --delete
          aws s3 sync s3://dev-dl-970892252496-us-east-1-raw/consolidated_raw/supplier_profile/ s3://dev-dl-970892252496-us-east-1-conformed/sync_test/supplier_profile/ --delete
        else
          echo "Starting sync for only provided s3 folder path $SPECIFIC_FOLDER_PATH"
          #aws s3 sync s3://dev-dl-970892252496-us-east-1-raw/consolidated_raw/ s3://dev-dl-970892252496-us-east-1-conformed/sync_test/ --delete --exclude '*' --include '$SPECIFIC_FOLDER_PATH'
        fi
  post_build:
    commands:
      - echo Build completed on `date`
      - | 
          aws athena --region us-east-1 start-query-execution --query-string "MSCK REPAIR TABLE standardized_customer_profile" --query-execution-context Database=publish_sync_test --result-configuration OutputLocation=s3://dev-dl-970892252496-us-east-1-queries
          aws athena --region us-east-1 start-query-execution --query-string "MSCK REPAIR TABLE standardized_product_profile" --query-execution-context Database=publish_sync_test --result-configuration OutputLocation=s3://dev-dl-970892252496-us-east-1-queries
          aws athena --region us-east-1 start-query-execution --query-string "MSCK REPAIR TABLE standardized_sales_order_detail" --query-execution-context Database=publish_sync_test --result-configuration OutputLocation=s3://dev-dl-970892252496-us-east-1-queries
          aws athena --region us-east-1 start-query-execution --query-string "MSCK REPAIR TABLE standardized_supplier_profile" --query-execution-context Database=publish_sync_test --result-configuration OutputLocation=s3://dev-dl-970892252496-us-east-1-queries
       
