version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - #aws s3 sync s3://raw-source s3://sync-destination --delete
      - echo ${SPECIFIC_FOLDER}
      - |
        #!/bin/bash
        if [[ " ${SPECIFIC_FOLDER[*]} " == *"test"* ]]; then
          # Iterate only through BRANCH_NAME directory
          echo "test param"
        else
          # Iterate through both dev and prod directories
          echo "not test"
        fi
  post_build:
    commands:
      - echo Build completed on `date`
